#!/usr/bin/env bash
# Since we’re placing our web servers behind a
# load balancer for this project, we want to add
# a custom Nginx response header

sudo apt update
sudo apt install -y nginx
HOSTNAME=$(hostname)
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default
sudo systemctl reload nginx

# Display a message indicating the configuration is complete
echo "Nginx has been configured on $HOSTNAME with the custom header X-Served-By."
