#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy
server_config=\
"
frontend mira-frontend
        bind *:80
        mode http
        default_backend mira-backend
backend mira-backend
        balance roundrobin
        server 510027-web-01 100.26.255.59:80 check
        server 510027-web-02 54.158.183.1:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
