#!/usr/bin/env bash
# Your machine has an SSH configuration file
# for the local SSH client
Host *
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    PasswordAuthentication no
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 34.201.61.222
    User ubuntu
